---
title: "2024 TMWH Delegation Schedule"
---

The schedule for the TMWH delegation visit to the Republic of Somaliland:

**Delegation Members**:

- Specialists: Superintendent Dr. Tsan-Hon Liou, Deputy Superintendent Dr. Chen-Yuan Chiang; HQ of TMM, Director Dr. Chen Chin-I, Deputy Director Dr. Chen Yu-Pin, and Cancer Center Dr. Chiou Tzeon-Jye.

- Administrative Staff: Wu Hua-Lun, Tseng Yu-Ping


### Thursday, May 9, 2024

14:30 | Flight from Bole International Airport (ADD), Ethiopia, arrive Hargeisa International Airport (HGA), Somaliland

(Mr. Chris Lee, accompanied by the Deputy Ambassador, will be present at the airport to welcome and receive the delegation team from Taipei Municipal Wanfang Hospital, TMWH)


16:00 - 17:00 | Visit to Taiwan Representative Office in Somaliland (TRO), Amb. Lou, and Mr. Chris Lee

  - Public Health projects by TMM (e.g., Dengue Fever prevention and control)
  - Collaborative Synergy: The Power of TMM and HGH's Partnership

18:00 - 20:00 | Dinner with TMM at Damal Hotel Restaurant;
Hargeisa Group Hospital, Director, Dr. Abdirahman, and Deputy Director, Dr. Adnan, and orthopedic Dr. Hassan.

<!-- (inviting) MoHD director general Dr. Hergeye; -->

Accommodation at Carro Edeg Hotel

### Friday, May 10, 2024 | Day off | 

09:00 - 11:00 | Morning meeting (Carro Edeg Hotel)

11:00 - 12:00 | Visit to Taiwan Medical Mission (TMM) in Somaliland

13:00 | Lunch break

14:00 - 15:00 | Dr. Hassan introducing OT, arthroscopic set, POP, ward, emergency to orthopedic Dr. Chen, in Hargeisa Group Hospital

accompanied with orthopedic residents, and OT director Mr. Ahmed

16:00 - 18:00 | Caano geel farm (Garas) 現擠駱駝鮮奶 

18:00 | Dinner


### Saturday, May 11, 2024

08:30 - 13:00 | **2024 Multidisciplinary Specialty Conference (2024MSC)** at Carro Edeg Hotel (https://texchi2.github.io/2024MSC/agenda.html)

Lunch break included
               
17:55         | Departure from Hargeisa International Airport (HGA)
