project:
  type: website
  output-dir: docs

website:
  title: "2024MSC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - agenda.qmd
      - href: h2023MSC.qmd
        text: "2023MSC"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



