project:
  type: website
  output-dir: docs

website:
  title: "2024MSC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda
      - href: abstract_uploads.qmd
        text: Abstract and keynote
      - href: project_HGH_laparoscopicCentre.qmd
        text: Laparoscopic Centre
      - href: thanks.qmd
        text: Acknowledgements
      - href: questionnaire.qmd
        text: Questionnaire
      - href: h2023MSC.qmd
        text: "2023MSC"
      - href: about.qmd
        text: About TMM

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



