project:
  type: website
  output-dir: docs

website:
  title: "2024MSC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda
      - href: abstract_uploads.qmd
        text: Abstract and keynote
      - href: registration_form.qmd
        text: Registration
      - href: project_HGH_laparoscopicCentre.qmd
        text: Laparoscopic Centre
      - href: h2023MSC.qmd
        text: "2023MSC"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



